<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simple_rss"
 *
 * Auto generated by Extension Builder 2018-10-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Simple RSS/Atom Reader',
    'description' => 'Read RSS and Atom Feeds. Based on Simple Pie Package',
    'category' => 'plugin',
    'author' => 'Benjamin Riezler',
    'author_email' => 'b.riezler@pixel-ink.de',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.6',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.1-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
